# Generated by Django 4.1.3 on 2022-11-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(default='', editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.TextField()),
                ('end_location', models.TextField()),
                ('date_and_time', models.TextField()),
                ('travel_medium', models.CharField(choices=[('BUS', 'Bus'), ('CAR', 'Car'), ('TRAIN', 'Train')], max_length=50)),
                ('assets_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.TextField()),
                ('end_location', models.TextField()),
                ('date_and_time', models.TextField()),
                ('assets_quantity', models.IntegerField()),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('TRAVEL_BAG', 'Travel Bag'), ('PACKAGE', 'Package')], max_length=50)),
                ('sensitivity', models.CharField(choices=[('HIGHLY_SENSITIVE', 'Highly Sensitive'), ('SENSITIVE', 'Sensitive'), ('NORMAL', 'Normal')], max_length=50)),
                ('whom_to_deliver', models.TextField()),
                ('requester_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.requester')),
            ],
        ),
    ]
