# Generated by Django 4.1.3 on 2022-11-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='requester_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.requester'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
