# Generated by Django 4.1.3 on 2022-11-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assets_requester_id_alter_requester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
