# Generated by Django 4.1.3 on 2022-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='assets',
            name='date_and_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assets',
            name='end_location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assets',
            name='start_location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assets',
            name='whom_to_deliver',
            field=models.TextField(default=''),
        ),
    ]
